api_version = "2026-07"

[[extensions]]
name = "t:name"
handle = "partial-payment-transform"

uid = "961ccfb0-b767-61b6-b622-c2d5011cbcae1a115328"
type = "function"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.transform.run"
  input_query = "src/cart_transform_run.graphql"
  export = "cart-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"
